name: A workflow for my Hello World file
on: pull_request

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: checkGit
        run: |
          echo ${{ github.context.payload }}











