name: A workflow for my Hello World file
on: pull_request

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Dump GitHub context
        env:
            GITHUB_CONTEXT: ${{ toJson(github.event.pull_request) }}
        run: echo "$GITHUB_CONTEXT"











