name: Auto Merge

on:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    name: Auto Merge
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/merges
          repository: ${{ github.repository }}
          prnum: ${{ github.event.pull_request.number }}
          mediaType: | # The | is significant!
            previews:
              - antiope
          head: ${{ github.event.head.ref }}
          base: ${{ github.event.base.ref }}
          commit_message: ${{ github.event.title }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
