name: A workflow for my Hello World file
on: pull_request

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Update status on commit
        run: |
          chmod +x ./action-a/git-message.sh
          ./action-a/git-message.sh $GITHUB_REPOSITORY ${{ env.GITHUB_TOKEN }}
