name: A workflow for my Hello World file
on:
  pull_request:
    types:
      - submitted
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/merges
          repository: ${{ github.repository }}
          prnum: ${{ github.event.pull_request.number }}
          mediaType: | # The | is significant!
            previews:
              - antiope
          head: ${{ github.head_ref }}
          base: ${{ github.base_ref }}
          commit_message: ${{ github.event.head_commit.message }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
